server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hoteles-service
          uri: lb://hoteles-service
          predicates:
            - Path=/hoteles/**
        - id: vuelos-service
          uri: lb://vuelos-service
          predicates:
            - Path=/vuelos/**
        - id: reservas-service
          uri: lb://reservas-service
          predicates:
            - Path=/reservas/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true