server:
  port: 8083

spring:
  application:
    name: reservas-service
  datasource:
    url: jdbc:mysql://localhost:3306/reservas_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
